### ISSUE TITLE
我建议你整理一下你的代码缩进

### ISSUE THREAD

**Issue by ice1000** [zsyh9612/Android_Volume#1]
就算你大括号不换行 缩进成这样也太过分了。。
看着眼睛疼。。。 :-1: 
好好整理下 对大家都有好处。
都是中国人我就不说英语了。

**Comment by ice1000** [comment]
。看起来死人一个，我还是别管闲事了

**Comment by zsyh** [comment]
回得晚了不好意思，这是我在git的第一个项目，谢谢指正

**Comment by zsyh** [comment]
对git的使用还不是很熟练，望谅解

**Comment by ice1000** [comment]
没说你git的问题，我是说你的代码缩进！
:angry:

**Comment by ice1000** [comment]
按理说我issue你之后github会给你发邮件的，你平时不用邮箱吗

**Comment by zsyh** [comment]
-代码缩进已经在最近的一次commit中整理了
-不熟练的结果就是看了邮件之后忘了。。。

**Comment by ice1000** [comment]
还有，你应该删除apk之外的所有目标文件
看着你用Eclipse各种不爽

**Comment by ice1000** [comment]
喂喂喂

**Comment by ice1000** [comment]
为啥你把那些.class也全上传上来了 :-1: 
:astonished:

**Comment by ice1000** [comment]
喂喂喂

**Comment by zsyh** [comment]
那时候还不会设置.gitignore，所以都传上来了。其实我现在已经换用android studio开发了，这些老项目还没有全部转移过去

**Comment by ice1000** [comment]
。 good。
换AS是好事啊，起码IDE用对了。
期待你选择正确的语言那一天（Kotlin
